import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import styles from "./page.module.css";

import NavElements from "./_components/NavElements";

export const metadata = {
  title: "First next app",
  description: "Generated by create next app",
};

const navItems = [
  {
    id: 1,
    title: "Home",
    href: "/",
  },
  {
    id: 2,
    title: "Posts",
    href: "/posts/1",
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.homeLayout}>
          <NavElements navItems={navItems} />
          {children}
        </div>
      </body>
    </html>
  );
}
